name: Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy app
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        
        script: |
          cd curly-robot # enter into folder
          git pull git@github.com:stuartelimu/curly-robot.git # pull recent changes from github
          echo 'Deplyment was successful 🚀'
