name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: gh-action-insecure-4kf7h-fl_&99))f5!b&k&=4!+vz8iuq-7pcr)2*l77n9@=-^w@
      DJANGO_SETTINGS_MODULE: src.settings.gh-action

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: cache dependency # caching dependency to make our build faster
      uses: actions/cache@v2
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

  deploy:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        
        script: |
          cd curly-robot # enter into folder
          git pull # pull recent changes from github
          source env/bin/activate
          pip install -r requirements.txt
          echo 'Deplyment was successful 🚀'
